# items around a certain place
WITH {
  SELECT DISTINCT
    ?coords ?periodical ?pubPlace ?dateOnset
  WHERE {
    INCLUDE %periodicals                      # input data from another subquery
    wd:Q1218 wdt:P625 ?center.                # Jerusalem
    SERVICE wikibase:around {
      ?pubPlace wdt:P625 ?coords.             # get coordinates of locations
      bd:serviceParam wikibase:center ?center.
      bd:serviceParam wikibase:radius "150".  # radius around center in km
     }
  }
} as %area