# add this to top of the query:
PREFIX medium: <http://www.wikidata.org/entity/Q1002697>    # set a publication type: periodicals (wd:Q1002697), newspapers (wd:Q11032)
# all periodicals published at a date of interest
WITH {
  SELECT DISTINCT
    ?periodical ?pubPlace ?dateOfInterest ?dateOnset
  WHERE {
    VALUES ?dateOfInterest {"1910-06-01"^^xsd:dateTime}. # set a date of interest
    ?periodical wdt:P31/wdt:P279* medium: ;              # publication type
              (wdt:P571 | wdt:P580) ?dateOnset.
    FILTER(?dateOnset < ?dateOfInterest).                # limit to titles published before a specific date
    OPTIONAL{ ?periodical (wdt:P582 | wdt:P576) ?dateTerminus.} # exclude discontinued papers
    FILTER(!bound(?dateTerminus) || ?dateTerminus > ?dateOfInterest).
    ?periodical (wdt:P291|wdt:P159|wdt:P276|wdt:P495|wdt:P131 ) ?pubPlace. # locations (remove if not interested in mapping)
  }
  ORDER BY ?dateOnset
  LIMIT 40000
} AS %periodicals