# items with holdings
WITH {
  SELECT DISTINCT
   ?coords ?periodical ?pubPlace ?dateOnset
   ?catalogueId ?collection
  WHERE {
    INCLUDE %input # input data from another subquery
    {?periodical (wdt:P1042 |    # ZDB
                  wdt:P243 |     # OCLC
                  wdt:P1844 |    # Hathi
                  wdt:P6721 )    # KOBV
      ?catalogueId.}
    UNION
    {?periodical wdt:P195 ?collection}
  }
} as %holdings