# items with holdings
WITH {
  SELECT DISTINCT
   ?coords ?periodical ?pubPlace ?dateOnset
   ?catalogueId ?collection
  WHERE {
    INCLUDE %input # input data from another subquery
    # holdings: P1042=ZDB, P243=OCLC, P1844=Hathi, P6721=KOBV,
    #      P12239=shamela, P724=internet archive, P8091=ark
    {?periodical (wdt:P1042 | wdt:P243 | wdt:P1844 | wdt:P6721 | wdt:P12239 | wdt:P724 | wdt:P8091) ?catalogueId.}
    UNION
    {?periodical wdt:P195 ?collection}
  }
} as %holdings