#title: الصحافة العربية حتى سنة ١٩٣٠
#defaultView:BubbleChart
PREFIX medium: <http://www.wikidata.org/entity/Q1002697> # set a publication type: periodicals (wd:Q1002697), newspapers (wd:Q11032)
SELECT DISTINCT
  ?title (COUNT (DISTINCT ?periodical) as ?count)
WITH {
  SELECT DISTINCT
    ?periodical ?dateOnset #(YEAR(?dateOnset) as ?yearOnset)
  WHERE {
    hint:SubQuery hint:runOnce true .    # this might save some time
    VALUES ?dateOfInterest {"1930-01-01"^^xsd:dateTime }. # set a date of interest
    VALUES ?lang {          # select publication languages
      wd:Q13955             # Arabic
#      wd:Q36730             # Ottoman Turkish
#      wd:Q8785              # Armenian
#      wd:Q36155             # Coptic
#      wd:Q9129              # Greek
#      wd:Q9168              # Farsi
#      wd:Q36196             # Ladino
      }.
    ?periodical wdt:P31/wdt:P279* medium: ;              # limit to medium
              (wdt:P571 | wdt:P580) ?dateOnset.
    ?periodical wdt:P407/wdt:P279* ?lang.            # limit by publication language
    FILTER(?dateOnset < ?dateOfInterest).                # published before a specific date
  }
  ORDER BY ?dateOnset
  LIMIT 4000
} as %periodicals
WHERE {
  INCLUDE %periodicals # load subgraph
  ?periodical wdt:P1476 ?title. # retrieve titles
  FILTER(LANG(?title) = 'ar'). # limit titles to Arabic strings
}
GROUP BY ?title #?yearOnset
HAVING(?count > 1) # set a threshold
ORDER BY DESC(?count)
LIMIT 200

# URL to query results: https://query-chest.toolforge.org/redirect/IR5nCxJ7FA2YEU2gsS42iemKeoaoyUMUmIs2GgOEOwv