#title: الصحافة العربية في أمريكا اللاتينية حتى سنة ١٩٣٠
#title:
#defaultView:Map{"hide":["?coords", "?pubPlace", "lang"], "markercluster": "true"}
SELECT DISTINCT
  ?coords
  (URI( CONCAT ("https://reasonator.toolforge.org/?&q=", STRAFTER(STR(?periodical), STR(wd:) ))) as ?item) # link to item on Reasonator
  # (URI(str(?periodical)) as ?item) # link to the wikidata item
  (CONCAT(?periodicalLabel, ": ", ?periodicalDesc) as ?itemLabel) # construct a label for the item
  #?lang
WITH {
  SELECT DISTINCT
    ?periodical ?dateOnset ?lang
  WHERE {
    VALUES ?dateOfInterest {"1930-01-01"^^xsd:dateTime}.
    VALUES ?lang {          # select publication languages
      wd:Q13955             # Arabic
#      wd:Q36730             # Ottoman Turkish
#      wd:Q8785              # Armenian
#      wd:Q36155             # Coptic
#      wd:Q9129              # Greek
#      wd:Q9168              # Farsi
#      wd:Q36196             # Ladino
      }.
    ?periodical wdt:P31/wdt:P279* wd:Q1002697;
              (wdt:P571 | wdt:P580) ?dateOnset;
              wdt:P407/wdt:P279* ?lang.
    FILTER(?dateOnset < ?dateOfInterest).                   # published before a specific date
  }
  LIMIT 40000
} as %periodicals
WITH {
  SELECT DISTINCT
    ?periodical ?pubPlace ?dateOnset ?lang
  WHERE {
    INCLUDE %periodicals
    ?periodical (wdt:P291|wdt:P159|wdt:P276|wdt:P495|wdt:P131 ) ?pubPlace. # locations
    # get the country and region
    ?pubPlace wdt:P17 ?country .
    ?country wdt:P361 ?region .
    # filter for specific regions
    VALUES ?region {
      wd:Q12585  # Latin America
    }
  }
} as %area
WHERE {
    INCLUDE %area
    ?pubPlace wdt:P625 ?coords. # get coordinates of locations
    # get labels and descriptions
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "ar, [AUTO_LANGUAGE]".
        ?periodical rdfs:label ?periodicalLabel;
            schema:description ?periodicalDesc.
    }
}
ORDER BY ?dateOnset
LIMIT 4000

# URL of results: https://query-chest.toolforge.org/redirect/DcvuKDYvUO0eMYgGQE4IWg2eKsUOog0O0i6KeSuKEYs